### ISSUE TITLE
Helm installation is broken 

### ISSUE THREAD

**Issue by lechuk47** [redhat-cop/cert-utils-operator#124]
It seems that the helm chart is missing the service account. 

```
LAST SEEN   TYPE      REASON              OBJECT                                      MESSAGE
21m         Warning   FailedCreate        replicaset/cert-utils-operator-6995578fff   Error creating: pods "cert-utils-operator-6995578fff-" is forbidden: error looking up service account default/cert-utils-operator-controller-manager: serviceaccount "cert-utils-operator-controller-manager" not found
```

The operator image is missing too. 

```
 - args:
   - --leader-elect
   command:
   - /manager
   image: :v1.3.7
```
