### ISSUE TITLE
Add ServiceMonitor to allow Metrics to be sent to Prometheus

### ISSUE THREAD

**Issue by OchiengEd** [redhat-cop/cert-utils-operator#30]
Given the operator already exposes a metrics endpoint through a service, I recommend creating a `ServiceMonitor` to sink the metrics to Prometheus.

This will eliminate the need for manual intervention to accomplish this task.

**Comment by raffaelespazzoli** [comment]
should this be added to the helm chart or created by the operator when it starts?

**Comment by OchiengEd** [comment]
It should not matter where it is added. It however makes sense to create the `ServiceMonitor` after the metrics service.

An example would appear as shown below.

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-utils-service-monitor
  labels:
    role: metrics-sink
spec:
  selector:
    matchLabels:
      name: cert-utils-operator
  endpoints:
  - port: http-metrics
```
