### ISSUE TITLE
configmap injection seems to be generating a large number of events

### ISSUE THREAD

**Issue by raffaelespazzoli** [redhat-cop/cert-utils-operator#40]
investigate why configmap injection controller seems to be receiving an unlimited number of events.
when adding logs to the event filter:
```golang
	isAnnotatedConfigMap := predicate.Funcs{
		UpdateFunc: func(e event.UpdateEvent) bool {
			oldSecret, _ := e.MetaOld.GetAnnotations()[certAnnotationSecret]
			newSecret, _ := e.MetaNew.GetAnnotations()[certAnnotationSecret]
			log.V(1).Info("update func", "config map", e.MetaNew.GetName(), "annotation old", oldSecret, "annotation new", newSecret)
			return oldSecret != newSecret
		},
		CreateFunc: func(e event.CreateEvent) bool {
			_, ok1 := e.Meta.GetAnnotations()[certAnnotationSecret]
			log.V(1).Info("create func", "config map", e.Meta.GetName(), "has annotation", ok1)
			return ok1
		},
	}
```
the operator seems to be entering an infinite loop in which all it does is printing those statements and discard the event.

**Comment by mathianasj** [comment]
@raffaelespazzoli do you have any steps to replicate the issue?  I was unable to witness that behavior.

Steps to try to reproduce
1. create secret
```
kind: Secret
apiVersion: v1
metadata:
  name: test-inject-ca
  namespace: cert-utils-testing
data:
  ca.crt: >-
    entry here
  tls.crt: >-
    entry here
  tls.key: >-
    entry here
type: kubernetes.io/tls
```
2. create configmap with annotation to reference secret
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: test-inject-ca-cm
  namespace: cert-utils-testing
  annotations:
    cert-utils-operator.redhat-cop.io/injectca-from-secret: cert-utils-testing/test-inject-ca
```
